version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rpg123
      MYSQL_DATABASE: rpgEncounter
      MYSQL_USER: admin
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: rpg123
    volumes:
      - my-datavolume:/var/lib/mysql

  fast-api:
    build: .
    # ports:
    #   - 8000:8000
    volumes:
      - .:/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fast-api

volumes:
  my-datavolume:
