version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_KEY}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: ${DB_ROOT_KEY}
    volumes:
      - my-datavolume:/var/lib/mysql

  fast-api:
    build: .
    # ports:
    #   - 8000:8000
    volumes:
      - .:/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  nginx:
    image: nginx:1.27.1
    container_name: nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fast-api

volumes:
  my-datavolume:
