version: "3.8"

services:
    mysql:
        image: mysql:latest
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: rpg123
            MYSQL_DATABASE: rpgEncounter
            MYSQL_USER: admin
            MYSQL_PORT: 3306
            MYSQL_PASSWORD: rpg123
        volumes:
            - my-datavolume:/var/lib/mysql

volumes:
    my-datavolume:
